FROM node:22-alpine AS builder

WORKDIR /Frontend
COPY . .
RUN npm install && \
    npm run build

FROM nginx:mainline-alpine3.23
COPY --from=builder /Frontend/* /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]