#
# Build
#
FROM maven:3.9.11 AS builder
COPY src /MyBackendApp
COPY pom.xml /MyBackendApp
RUN mvn -B -f /MyBackendApp/pom.xml clean package
#
# Package stage
#
FROM nginx:mainline-alpine3.23
COPY --from=build /MyBackendApp/target/projetjavafinal-1.0.0.jar /usr/local/lib/projetjavafinal.jar
ENTRYPOINT ["java","-jar","/usr/local/lib/projetjavafinal.jar"]